os: Windows Server 2012

environment:
  VisualStudioVersion: 12.0
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

configuration: Release

before_build:
  - nuget restore src\psbuild.sln

build_script:
  - ps: .\test.ps1

artifacts:
  - path: OutputRoot\**\*.psm1
  - path: OutputRoot\PSBuild\**\*.dll
  - path: OutputRoot\PSBuild\**\*.pdb
  - path: OutputRoot\**\*.nupkg
